name: CI Pipeline - Infra

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.4

    - name: Create terraform.tfvars
      run: |
        echo "aws_region = \"${{ secrets.AWS_REGION }}\"" > terraform.tfvars
        echo "aws_access_key_id = \"${{ secrets.AWS_ACCESS_KEY_ID }}\"" >> terraform.tfvars
        echo "aws_secret_access_key = \"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"" >> terraform.tfvars
        echo "aws_session_token = \"${{ secrets.AWS_SESSION_TOKEN }}\"" >> terraform.tfvars
        echo "cluster_name = \"${{ secrets.CLUSTER_NAME }}\"" >> terraform.tfvars
        echo "subnet_ids = [\"$(echo ${{ secrets.SUBNET_IDS }} | tr ',' '\",\"')\"]" >> terraform.tfvars
        echo "max_size_capacity = \"${{ secrets.MAX_SIZE_CAPACITY }}\"" >> terraform.tfvars
        echo "min_size_capacity = \"${{ secrets.MIN_SIZE_CAPACITY }}\"" >> terraform.tfvars
        echo "desired_capacity = \"${{ secrets.DESIRED_CAPACITY }}\"" >> terraform.tfvars
        echo "node_instance_type = \"${{ secrets.NODE_INSTANCE_TYPE }}\"" >> terraform.tfvars
        
    - name: Debug terraform.tfvars
      run: cat terraform.tfvars

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
