name: CI Pipeline - Infra

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.4



    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Check environment variables
      run: |
        echo "API Gateway Name: ${API_GATEWAY_NAME}"
        echo "Cognito Domain Name: ${COGNITO_DOMAIN_NAME}"
      env:
        API_GATEWAY_NAME: ${{ secrets.API_GATEWAY_NAME }}
        COGNITO_DOMAIN_NAME: ${{ secrets.COGNITO_DOMAIN_NAME }}
        
    - name: Terraform Plan
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        SUBNET_IDS: ${{ secrets.SUBNET_IDS }}
        MAX_SIZE_CAPACITY: ${{ secrets.MAX_SIZE_CAPACITY }}
        MIN_SIZE_CAPACITY: ${{ secrets.MIN_SIZE_CAPACITY }}
        DESIRED_CAPACITY: ${{ secrets.DESIRED_CAPACITY }}
        NODE_INSTANCE_TYPE: ${{ secrets.NODE_INSTANCE_TYPE }}
      run: |
        terraform plan -var="aws_region=${AWS_REGION}" \
                         -var="aws_access_key_id=${AWS_ACCESS_KEY_ID}" \
                         -var="aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" \
                         -var="aws_session_token=${AWS_SESSION_TOKEN}" \
                         -var="cluster_name=${CLUSTER_NAME}" \
                         -var="subnet_ids=${SUBNET_IDS}" \
                         -var="max_size_capacity=${MAX_SIZE_CAPACITY}" \
                         -var="min_size_capacity=${MIN_SIZE_CAPACITY}" \
                         -var="desired_capacity=${DESIRED_CAPACITY}" \
                         -var="node_instance_type=${NODE_INSTANCE_TYPE}"
